services:
  app:
    image: heeyoon1302/happyprocess:latest
    env_file:
      - .env
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: always
