INSERT INTO DISEASE (CONDITION_ID, CONDITION_NAME) VALUES (1, '질병 없음');
INSERT INTO DISEASE (CONDITION_ID, CONDITION_NAME) VALUES (2, '천식');
INSERT INTO DISEASE (CONDITION_ID, CONDITION_NAME) VALUES (3, '고혈압');
INSERT INTO DISEASE (CONDITION_ID, CONDITION_NAME) VALUES (4, '안구건조증');